### ISSUE TITLE
Meeting today

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/CardioPredict#10]
Hi guys,  we should definitely meet today in order to split the work and discuss how we want to proceed. I would suggest meeting within the next hour. What do you think?

**Comment by MDSFusionist** [comment]
<img width="1440" alt="windows_docker_test" src="https://github.com/UBC-MDS/CardioPredict/assets/150200738/f21a342b-b0da-4f3e-b7d1-f53e6c6bf865">
I  just wanted to update you all that I have successfully tested the Dockerfile on my Windows machine, and everything is working as expected. The build was completed without any issues, and the container is running smoothly. This should be a good indication that our Docker setup is compatible with Windows environments.

**Comment by sandygross** [comment]
Ok great. Thank you Doris for confirming! I will update it to today by pining some package versions and adding some packages that I installed for the pytest. I will also update Docker compose file. Would be great, if you can try it again then!

**Comment by MDSFusionist** [comment]
It works. 
<img width="689" alt="1700886879957" src="https://github.com/UBC-MDS/CardioPredict/assets/150200738/91534dff-6340-4d7e-aa89-b7a999737c48">
