### ISSUE TITLE
Restructuring of the repo

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/CardioPredict#13]
Hi Team, 
I would suggest we restructure out repo, in the sense that we put our notebook with our whole analysis into the 'src' folder. What  do you think?

**Comment by MDSFusionist** [comment]
I agree with reconstructing the folder. We can follow this instruction -"https://ubc-mds.slack.com/archives/C24HUNRJL/p1700614954428329". How about constructing a "doc" folder for .ipynb and .html, and leave test .py files in "src"?

**Comment by sandygross** [comment]
Yes that sounds great. Can you please do that?

**Comment by sandygross** [comment]
I changed the structure. What do you think of the new structure?
