### ISSUE TITLE
Suggested structure of scripts

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/CardioPredict#23]
Hello Team,

I'd love to get your feedback on my proposed script structure. Unlike the current notebook, the idea is to test only the model with the best recall_score (either Logistic Regression or KNN) on the test data. Following that, I can craft a new script utilizing the superior fitted model and returning the recall score. I shortly talked about this  with Tiff, and it does entail some adjustments in our writing section. Keen to hear your thoughts!

**Comment by MDSFusionist** [comment]
Hi Sandy, thank you so much for your dedication to seeking useful feedback from our instructor. It is very helpful. I've gone through the kNN scripts and made some refinements to produce accuracy and recall plots for our hyperparameter tuning, both with and without sampling. These visualizations, I believe, effectively represent the core strengths of our project.

Considering the compelling insights these models provide, I propose we temporarily sideline the logistic regression analysis to concentrate on detailing the kNN approach, which seems to be our project's focal point. This would streamline our narrative and highlight the kNN model's unique contributions to CVD risk prediction.
