### ISSUE TITLE
Final report review

### ISSUE THREAD

**Issue by MDSFusionist** [UBC-MDS/CardioPredict#27]
Dear Team,

I hope this message finds you well. I am reaching out to share the final draft of our report on the CVD risk prediction model. I would greatly appreciate it if you could take some time to review the document and provide your valuable feedback. Your insights are crucial to ensure the report's accuracy, coherence, and overall quality. Here is a checklist for next week's peer review. Let's adhere to it. Then next week we will have issues and feedback need to be addressed. 

### Analysis report

- [ ] **Authors:** Does the report include a list of authors with their affiliations?
- [ ] **What is the question:** Do the authors clearly state the research question being asked?
- [ ] **Importance:** Do the authors clearly state the importance for this research question?
- [ ] **Background**: Do the authors provide sufficient background information so that readers can understand the report?
- [ ] **Methods:** Do the authors clearly describe and justify the methodology used in the data analysis? Do the authors communicate any assumptions or limitations of their methodologies?
- [ ] **Results:** Do the authors clearly communicate their findings through writing, tables and figures?
- [ ] **Conclusions:** Are the conclusions presented by the authors correct? 
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [ ] **Writing quality:** Is the writing of good quality, concise, engaging?

**Comment by joeywwwu** [comment]
Hi Doris, thanks for wrapping up the final report, but I found there are some issues come up with EDA scripts, I will have to work on it and update with you later.

**Comment by joeywwwu** [comment]
> Hi Doris, thanks for wrapping up the final report, but I found there are some issues come up with EDA scripts, I will have to work on it and update with you later.

Problem fixed
