### ISSUE TITLE
Milestone 4 Peer Review

### ISSUE THREAD

**Issue by MDSFusionist** [UBC-MDS/CardioPredict#36]
Hello Team,

I'm thrilled to share that we've received some incredibly positive feedback from our recent peer review! 🎉 This is a testament to the hard work and dedication each of you has put into our project.

The reviewers were highly impressed with our progress and the quality of our work. However, there are some minor issues for us to address in the this week:

#### Review Comments: @shawnhu444

This project exemplifies a highly standardized approach to data analysis and software development, aligning with best practices in several key areas:

1. High code quality, functionality documentation and follow the community guidelines. These aspects are vital for maintaining and scaling the software efficiently, ensuring its long-term viability.

2. The code submitted ensures data accessibility by providing a complete computational methods and putting details, functions. These features significantly enhance the reproducibility and reliability of the research, which are cornerstones of scientific rigor.

3. Reporting: The comprehensive approach to reporting, including clear articulation of research questions, background, functions, and coupled with high-quality writing and complete referencing .This demonstrates an exemplary standard in code communication.

In summary, this project stands out for comprehensive documentation, code quality, reproducibility, and thorough analysis reporting.

#### Review Comments: @sungg888

1. Documentation: The project is good with its detailed documentation, easy installation, and usage examples. The inclusion of community guidelines significantly aids collaboration and user support.
2. Code Quality: The code is well-organized, readable, and adheres to style guidelines, enhancing its maintainability. The project also have clear and readable robust testing framework to test its reliability.
3. Reproducibility: The project excels in reproducibility, providing accessible raw data, comprehensive computational methods, and clear steps in Readme.
   Analysis Report: The analysis report is clear and detailed, effectively communicating the research question, methods, and results. The high-quality writing makes the report engaging and informative. The report covers all points in the rubric.
4. Overall, the project is a high-quality, reproducible research. And it meet the standards of review checklist.

#### Review Comments: @Rachel0619

Overall, the project is conducted in high-quality and I'm deeply impressed by your hard work.

1. I really appreciate the plotting part of the report. The figures are well made and organized.
2. Due to some reasons, after I git cloned the repo and ran docker compose up in the root folder, there's an error says: Error response from daemon: driver failed programming external connectivity on endpoint cardiopredict-disease_pred-1 (ca65c7817f322d11658c165784b27d8b6e5054acd8caa3412341e3be17081da4): Bind for 0.0.0.0:8888 failed: port is already allocated
   I have built the image successfully but not able to see the url starting with 127. Maybe double check with the reproducibility. This might not be a problem on your machine., just double check though.
3. Low recall might be an issue in the context of early detection and intervention a disease (if this is the research question of this project). You might want to try some other classification models to see if you can get higher recall.
4. The src file is a little bit messy now with different type of files in it.

#### Review Comments: @carrieyanyi

Please provide more detailed feedback here on what was done particularly well, and what could be improved. It is especially important to elaborate on items that you were not able to check off in the list above.

I really enjoy going through this project and gain some knowledge about Cardiovascular Disease. The overall structure of the project is well organized. Both figures and models have sufficient descriptions.

Installation:
Some issues were encountered when i runned the script.
EDA.py: "ValueError: Saving charts in 'png' format requires the vl-convert-python or altair_saver package: see [http://github.com/altair-viz/altair_saver/](https://github.com/altair-viz/altair_saver/)"

Reference: In the Data section, the citation for Tsao201 is mis-spelling, it should be Tsao2015 instead.

Visualization: It would be more obvious to add legend explanation in figure 5 to different what does disease 0 and 1 mean.

Abbreviation: A lot of terminology are used in the report, it would be great if maintaining consistency in the use of abbreviations, rather than alternating with their full names.

**Comment by sandygross** [comment]
Thanks a lot, Doris! I will clean up the src folder.

**Comment by MDSFusionist** [comment]
Dear Team, We addressed all the peer review issues by Wednesday night. We did a good job!
