### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/CardioPredict#39]
Hi guys, in the following I summarize some of feedback we receive for Milestone 2 and that we should implement in our current analysis:
- Add examples to the functions 'run_knn_analysis.py, logistic_regression_evaluation.py, and create_pairwise_scatter_plot.py' 
- Add tests for 'test_split.py', specifically create an edge-case input, e.g., where the paths are empty or not in the correct format
- In logistiic_regression_evaluation.py, it's better to use a Python dictionary with meaningful key names to return, instead of a tuple in which the output is based on order. (not as clear and meaningful)
Probably it would be good to address these issues in today's meeting.

**Comment by MDSFusionist** [comment]
@sandygross Thanks for putting them here. I will make sure we properly document the feedback in our CHANGELOG.md.

**Comment by MDSFusionist** [comment]
I also added examples and made the docstring more readable for read_csv written for milestone 3.

**Comment by MDSFusionist** [comment]
We addressed all the issues regarding to feedback on Milestone 2. All the changes have been documented in CHANGELOG.md.
