### ISSUE TITLE
Update Milestone 4

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/CardioPredict#42]
Dear Team,

I just review our notebook, ran all our tests via pytest, tested the container and the makefile again and reviewed the changelog file. Great job first of all! All tests seem run and I really love the Changelog file. I only modified small things!
I create a new html version of our jupyter book and the link is updated. Please check that and let me know if you want to do any further changes (unfortunately I cannot fix the top, but I talked with Tiff it is ok and will not be part of the grading).
If you do not have any further changes to make, I would suggest we can create the release.

**Comment by MDSFusionist** [comment]
Please proceed to make the release. Thank you.
